AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda to generate pre-signed S3 URLs + QR codes (uploads folder)

Parameters:
  UploadBucketName:
    Type: String
    Description: Name of the S3 bucket for CSV uploads
    Default: ranelagh-results-csv2

Resources:

  # Lambda execution role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: qr-upload-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: QRUploadLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Permission to put objects ONLY in uploads/ folder
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${UploadBucketName}/uploads/*
              # CloudWatch logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # Lambda function
  QRUploadLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: qr-upload-lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          BUCKET_NAME: !Ref UploadBucketName
          UPLOAD_PREFIX: uploads/
      Code:
        ZipFile: |
          import json
          import uuid
          import base64
          import boto3
          import qrcode
          from io import BytesIO
          import os

          s3 = boto3.client('s3')

          BUCKET_NAME = os.environ.get("BUCKET_NAME", "ranelagh-results-csv2")
          UPLOAD_PREFIX = os.environ.get("UPLOAD_PREFIX", "uploads/")

          def generate_qr_png(data: str) -> str:
              qr = qrcode.QRCode(
                  version=1,
                  error_correction=qrcode.constants.ERROR_CORRECT_M,
                  box_size=10,
                  border=4
              )
              qr.add_data(data)
              qr.make(fit=True)
              img = qr.make_image(fill_color="black", back_color="white")
              buffer = BytesIO()
              img.save(buffer, format="PNG")
              return base64.b64encode(buffer.getvalue()).decode("utf-8")

          def lambda_handler(event, context):
              # Unique token for this upload
              token = str(uuid.uuid4())
              object_key = f"{UPLOAD_PREFIX}{token}.csv"

              # Pre-signed URL for S3 PUT
              presigned_url = s3.generate_presigned_url(
                  ClientMethod='put_object',
                  Params={
                      "Bucket": BUCKET_NAME,
                      "Key": object_key,
                      "ContentType": "text/csv"
                  },
                  ExpiresIn=300
              )

              qr_png_b64 = generate_qr_png(token)

              return {
                  "statusCode": 200,
                  "headers": {"Content-Type": "application/json"},
                  "body": json.dumps({
                      "token": token,
                      "upload_url": presigned_url,
                      "s3_key": object_key,
                      "qr_png_base64": qr_png_b64
                  })
              }

  # API Gateway
  QRUploadApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: qr-upload-api
      Description: API Gateway for QR upload Lambda

  QRUploadApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref QRUploadApi
      ParentId: !GetAtt QRUploadApi.RootResourceId
      PathPart: upload

  QRUploadApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref QRUploadApi
      ResourceId: !Ref QRUploadApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${QRUploadLambda.Arn}/invocations

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref QRUploadLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${QRUploadApi}/*/*/upload

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref QRUploadLambda

  ApiEndpoint:
    Description: API Gateway endpoint for QR upload
    Value: !Sub https://${QRUploadApi}.execute-api.${AWS::Region}.amazonaws.com/prod/upload
